### ISSUE TITLE
Pandas versioning issue

### ISSUE THREAD

**Issue by DimitrisAlivas** [AstraZeneca/rexmex#51]
Hey rexmex team,

I wanted to ask you if there is a specific reason why your installation requires pandas to be of this version? 

Since this package gets installed with the latest version of PyKEEN, I am facing some versioning issues due to the Pandas version restriction of your package. 

The related line of code:
https://github.com/AstraZeneca/rexmex/blob/44f453ff20e92569270b9e1cfcb75b44b7839128/setup.py#L3

Apologies if it's a silly question but: is it indeed a strict requirement for rexmex to have Pandas<1.3.5 or is this something we can modify in `rexmex` setup.py? ( if so I can open a related PR for it ) 

Thank you in advance!
Best,
Dimitris

**Comment by GavEdwards** [comment]
Hi @DimitrisAlivas, thanks for getting in touch.

We should be able to remove the Pandas version requirement. I tested it locally and it works fine.

I made a draft PR but there are some issues within build pipelines for package versions. However I think the issue is isolated to just the build environment. 

I'll try to fix the build pipeline when I get chance to enable this change. If that works we can release a new version of RexMex to solve this issue.

Thanks,
Gav
